<?php
$EM_CONF[$_EXTKEY] = array(
    'title'            => 'Hilzweb.com Template',
    'description'      => 'This extension provides templates and custom content elements for hilzweb.com.',
    'category'         => 'misc',
    'author'           => 'Simon Hilz',
    'author_email'     => 'sh@hilzweb.com',
    'author_company'   => 'Hilzweb.com',
    'shy'              => '',
    'dependencies'     => 'cms,extbase,fluidflux,fluidpages,fluidcontent,vhs',
    'conflicts'        => '',
    'priority'         => '',
    'module'           => '',
    'state'            => 'experimental',
    'internal'         => '',
    'uploadfolder'     => 1,
    'createDirs'       => '',
    'modify_tables'    => '',
    'clearCacheOnLoad' => 1,
    'lockType'         => '',
    'version'          => '0.1',
    'constraints'      => array(
        'depends'   => array(
            'typo3'        => '6.2-6.2.99',
            'cms'          => '',
            'extbase'      => '',
            'fluid'        => '',
            'flux'         => '',
            'fluidpages'   => '',
            'fluidcontent' => '',
            'vhs'          => '',
        ),
        'conflicts' => array(),
        'suggests'  => array(),
    ),
    'suggests'         => array(),
);